#!/bin/sh

LOG_FILE="./kiosk.log"

{
  xset -dpms
  xset s off
  xset s noblank

  while true; do
    DISPLAY_ID=$(xrandr | grep " connected" | grep -v "eDP" | awk '{print $1}' | head -n 1)

    if [ -n "$DISPLAY_ID" ]; then
      break
    fi

    sleep 1
  done

  cd ~/Prog/saros_gui/
  . ~/.nvm/nvm.sh
  nvm use
  yarn dev &

  until curl -s http://localhost:3000 > /dev/null; do
    sleep 1
  done

  DISPLAY_ID=$(xrandr | grep " connected" | grep -v "eDP" | awk '{print $1}' | head -n 1)
  xrandr --output eDP-1 --off

  if [ -z "$DISPLAY_ID" ]; then
    echo "No external display found"
  else
    echo "Found external display: $DISPLAY_ID"
  fi

  read -r PROFILE_PATH < ./.firefox-profile-path

  firefox --no-remote --kiosk --profile "$PROFILE_PATH" --window-position=0,0 --width=1920 --height=1080 http://localhost:3000
} > "$LOG_FILE" 2>&1
